version: '3.0'

services:
    zabbix-frontend:
        image: zabbix/zabbix-web-apache-mysql:alpine-5.0-latest
        container_name: zabbix-web
        environment:
            - ZBX_SERVER_HOST=zabbix-server
            - ZBX_SERVER_PORT=10051
            - DB_SERVER_HOST=172.17.0.1
            - DB_SERVER_PORT=3306
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_password
            - PHP_TZ=America/Sao_Paulo
        depends_on:
            - zabbix-server
        links:
            - zabbix-server
        ports:
            - '8080:8080'
        restart: always

    zabbix-server:
        image: zabbix/zabbix-server-mysql:alpine-5.0-latest
        container_name: zabbix-server
        environment:
            - DB_SERVER_HOST=172.17.0.1
            - DB_SERVER_PORT=3306
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_password
        ports:
            - '10051:10051'
        restart: always

